run:
  timeout: 5m
  skip-dirs:
    - .history
    - vendor

linters:
  disable:
    - dupl
    - errcheck
    - ineffassign
    - gosimple
  enable:
    - gofmt
    - govet

# Removed linters-settings as it is not allowed

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
