run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - exportloopref
    - gocyclo
    - misspell
    - unconvert
    - dupl
    - goconst

linters-settings:
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
    - path: main\.go
      linters:
        - gocyclo
