run:
  timeout: 5m
  skip-dirs:
    - .history
    - vendor

linters:
  disable:
    - dupl # Code duplication
    - errcheck # Unchecked errors
  enable:
    - gofmt # Code formatting
    - govet # Go vet
    - staticcheck
    - gosimple
    - unused

linters-settings:
  dupl:
    threshold: 200
  errcheck:
    check-blank: false

issues:
  exclude-use-default: false
