// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalizedString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uz            string                 `protobuf:"bytes,1,opt,name=uz,proto3" json:"uz,omitempty"`
	Ru            string                 `protobuf:"bytes,2,opt,name=ru,proto3" json:"ru,omitempty"`
	En            string                 `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedString) Reset() {
	*x = LocalizedString{}
	mi := &file_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedString) ProtoMessage() {}

func (x *LocalizedString) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedString.ProtoReflect.Descriptor instead.
func (*LocalizedString) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{0}
}

func (x *LocalizedString) GetUz() string {
	if x != nil {
		return x.Uz
	}
	return ""
}

func (x *LocalizedString) GetRu() string {
	if x != nil {
		return x.Ru
	}
	return ""
}

func (x *LocalizedString) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

type AttributeOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         *LocalizedString       `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeOption) Reset() {
	*x = AttributeOption{}
	mi := &file_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeOption) ProtoMessage() {}

func (x *AttributeOption) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeOption.ProtoReflect.Descriptor instead.
func (*AttributeOption) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AttributeOption) GetLabel() *LocalizedString {
	if x != nil {
		return x.Label
	}
	return nil
}

type CategoryAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // text, number, dropdown, switch
	Label         *LocalizedString       `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Options       []*AttributeOption     `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	IsRequired    bool                   `protobuf:"varint,7,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryAttribute) Reset() {
	*x = CategoryAttribute{}
	mi := &file_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAttribute) ProtoMessage() {}

func (x *CategoryAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAttribute.ProtoReflect.Descriptor instead.
func (*CategoryAttribute) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryAttribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryAttribute) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CategoryAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CategoryAttribute) GetLabel() *LocalizedString {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *CategoryAttribute) GetOptions() []*AttributeOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CategoryAttribute) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *CategoryAttribute) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryAttribute) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CategoryAttribute) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          *LocalizedString       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	IconUrl       string                 `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	ProductCount  int32                  `protobuf:"varint,8,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	SubCategories []*Category            `protobuf:"bytes,9,rep,name=sub_categories,json=subCategories,proto3" json:"sub_categories,omitempty"`
	Attributes    []*CategoryAttribute   `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty"` // Optional: include attributes with category
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Category) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Category) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Category) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Category) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *Category) GetSubCategories() []*Category {
	if x != nil {
		return x.SubCategories
	}
	return nil
}

func (x *Category) GetAttributes() []*CategoryAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Flat category for admin list views
type FlatCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ParentName    string                 `protobuf:"bytes,3,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	Name          *LocalizedString       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	ProductCount  int32                  `protobuf:"varint,8,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatCategory) Reset() {
	*x = FlatCategory{}
	mi := &file_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatCategory) ProtoMessage() {}

func (x *FlatCategory) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatCategory.ProtoReflect.Descriptor instead.
func (*FlatCategory) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{4}
}

func (x *FlatCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlatCategory) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *FlatCategory) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *FlatCategory) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *FlatCategory) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *FlatCategory) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *FlatCategory) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *FlatCategory) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

type ListCategoriesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly        bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	IncludeAttributes bool                   `protobuf:"varint,2,opt,name=include_attributes,json=includeAttributes,proto3" json:"include_attributes,omitempty"` // Whether to include attributes in response
	Flat              bool                   `protobuf:"varint,3,opt,name=flat,proto3" json:"flat,omitempty"`                                                    // Return flat list instead of tree (for admin)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{5}
}

func (x *ListCategoriesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListCategoriesRequest) GetIncludeAttributes() bool {
	if x != nil {
		return x.IncludeAttributes
	}
	return false
}

func (x *ListCategoriesRequest) GetFlat() bool {
	if x != nil {
		return x.Flat
	}
	return false
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{6}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoriesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListFlatCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*FlatCategory        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlatCategoriesResponse) Reset() {
	*x = ListFlatCategoriesResponse{}
	mi := &file_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlatCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlatCategoriesResponse) ProtoMessage() {}

func (x *ListFlatCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlatCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListFlatCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{7}
}

func (x *ListFlatCategoriesResponse) GetCategories() []*FlatCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListFlatCategoriesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCategoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeAttributes bool                   `protobuf:"varint,2,opt,name=include_attributes,json=includeAttributes,proto3" json:"include_attributes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{8}
}

func (x *GetCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCategoryRequest) GetIncludeAttributes() bool {
	if x != nil {
		return x.IncludeAttributes
	}
	return false
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          *LocalizedString       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_category_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCategoryRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCategoryRequest) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreateCategoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateCategoryRequest) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CreateCategoryRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          *LocalizedString       `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,4,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	IconUrl       *string                `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	IsActive      *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_category_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateCategoryRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateCategoryRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_category_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCategoryAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryAttributesRequest) Reset() {
	*x = ListCategoryAttributesRequest{}
	mi := &file_category_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryAttributesRequest) ProtoMessage() {}

func (x *ListCategoryAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoryAttributesRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{13}
}

func (x *ListCategoryAttributesRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type ListCategoryAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*CategoryAttribute   `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryAttributesResponse) Reset() {
	*x = ListCategoryAttributesResponse{}
	mi := &file_category_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryAttributesResponse) ProtoMessage() {}

func (x *ListCategoryAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryAttributesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoryAttributesResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{14}
}

func (x *ListCategoryAttributesResponse) GetAttributes() []*CategoryAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ListCategoryAttributesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCategoryAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryAttributeRequest) Reset() {
	*x = GetCategoryAttributeRequest{}
	mi := &file_category_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryAttributeRequest) ProtoMessage() {}

func (x *GetCategoryAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryAttributeRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{15}
}

func (x *GetCategoryAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CategoryAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     *CategoryAttribute     `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryAttributeResponse) Reset() {
	*x = CategoryAttributeResponse{}
	mi := &file_category_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAttributeResponse) ProtoMessage() {}

func (x *CategoryAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAttributeResponse.ProtoReflect.Descriptor instead.
func (*CategoryAttributeResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{16}
}

func (x *CategoryAttributeResponse) GetAttribute() *CategoryAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type CreateCategoryAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // text, number, dropdown, switch
	Label         *LocalizedString       `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Options       []*AttributeOption     `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	IsRequired    bool                   `protobuf:"varint,6,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryAttributeRequest) Reset() {
	*x = CreateCategoryAttributeRequest{}
	mi := &file_category_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryAttributeRequest) ProtoMessage() {}

func (x *CreateCategoryAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryAttributeRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryAttributeRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCategoryAttributeRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateCategoryAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateCategoryAttributeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCategoryAttributeRequest) GetLabel() *LocalizedString {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *CreateCategoryAttributeRequest) GetOptions() []*AttributeOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateCategoryAttributeRequest) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *CreateCategoryAttributeRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Label         *LocalizedString       `protobuf:"bytes,4,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Options       []*AttributeOption     `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"` // Replaces all options
	IsRequired    *bool                  `protobuf:"varint,6,opt,name=is_required,json=isRequired,proto3,oneof" json:"is_required,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryAttributeRequest) Reset() {
	*x = UpdateCategoryAttributeRequest{}
	mi := &file_category_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryAttributeRequest) ProtoMessage() {}

func (x *UpdateCategoryAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryAttributeRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryAttributeRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCategoryAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryAttributeRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *UpdateCategoryAttributeRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateCategoryAttributeRequest) GetLabel() *LocalizedString {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *UpdateCategoryAttributeRequest) GetOptions() []*AttributeOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateCategoryAttributeRequest) GetIsRequired() bool {
	if x != nil && x.IsRequired != nil {
		return *x.IsRequired
	}
	return false
}

func (x *UpdateCategoryAttributeRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

type DeleteCategoryAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryAttributeRequest) Reset() {
	*x = DeleteCategoryAttributeRequest{}
	mi := &file_category_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryAttributeRequest) ProtoMessage() {}

func (x *DeleteCategoryAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryAttributeRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryAttributeRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCategoryAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_category_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{20}
}

var File_category_proto protoreflect.FileDescriptor

const file_category_proto_rawDesc = "" +
	"\n" +
	"\x0ecategory.proto\x12\bcategory\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x0fLocalizedString\x12\x0e\n" +
	"\x02uz\x18\x01 \x01(\tR\x02uz\x12\x0e\n" +
	"\x02ru\x18\x02 \x01(\tR\x02ru\x12\x0e\n" +
	"\x02en\x18\x03 \x01(\tR\x02en\"X\n" +
	"\x0fAttributeOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12/\n" +
	"\x05label\x18\x02 \x01(\v2\x19.category.LocalizedStringR\x05label\"\x86\x03\n" +
	"\x11CategoryAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12/\n" +
	"\x05label\x18\x05 \x01(\v2\x19.category.LocalizedStringR\x05label\x123\n" +
	"\aoptions\x18\x06 \x03(\v2\x19.category.AttributeOptionR\aoptions\x12\x1f\n" +
	"\vis_required\x18\a \x01(\bR\n" +
	"isRequired\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x05R\tsortOrder\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xee\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12-\n" +
	"\x04name\x18\x03 \x01(\v2\x19.category.LocalizedStringR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x19\n" +
	"\bicon_url\x18\x05 \x01(\tR\aiconUrl\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12#\n" +
	"\rproduct_count\x18\b \x01(\x05R\fproductCount\x129\n" +
	"\x0esub_categories\x18\t \x03(\v2\x12.category.CategoryR\rsubCategories\x12;\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2\x1b.category.CategoryAttributeR\n" +
	"attributes\"\x87\x02\n" +
	"\fFlatCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x1f\n" +
	"\vparent_name\x18\x03 \x01(\tR\n" +
	"parentName\x12-\n" +
	"\x04name\x18\x04 \x01(\v2\x19.category.LocalizedStringR\x04name\x12\x19\n" +
	"\bicon_url\x18\x05 \x01(\tR\aiconUrl\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12#\n" +
	"\rproduct_count\x18\b \x01(\x05R\fproductCount\"{\n" +
	"\x15ListCategoriesRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12-\n" +
	"\x12include_attributes\x18\x02 \x01(\bR\x11includeAttributes\x12\x12\n" +
	"\x04flat\x18\x03 \x01(\bR\x04flat\"b\n" +
	"\x16ListCategoriesResponse\x122\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x12.category.CategoryR\n" +
	"categories\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"j\n" +
	"\x1aListFlatCategoriesResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.category.FlatCategoryR\n" +
	"categories\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"S\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x12include_attributes\x18\x02 \x01(\bR\x11includeAttributes\"B\n" +
	"\x10CategoryResponse\x12.\n" +
	"\bcategory\x18\x01 \x01(\v2\x12.category.CategoryR\bcategory\"\xce\x01\n" +
	"\x15CreateCategoryRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.category.LocalizedStringR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"\xc6\x02\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x122\n" +
	"\x04name\x18\x03 \x01(\v2\x19.category.LocalizedStringH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x04 \x01(\tH\x02R\x04slug\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\x05 \x01(\tH\x03R\aiconUrl\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x04R\bisActive\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05H\x05R\tsortOrder\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slugB\v\n" +
	"\t_icon_urlB\f\n" +
	"\n" +
	"_is_activeB\r\n" +
	"\v_sort_order\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x1dListCategoryAttributesRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"s\n" +
	"\x1eListCategoryAttributesResponse\x12;\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x1b.category.CategoryAttributeR\n" +
	"attributes\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"-\n" +
	"\x1bGetCategoryAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x19CategoryAttributeResponse\x129\n" +
	"\tattribute\x18\x01 \x01(\v2\x1b.category.CategoryAttributeR\tattribute\"\x8d\x02\n" +
	"\x1eCreateCategoryAttributeRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12/\n" +
	"\x05label\x18\x04 \x01(\v2\x19.category.LocalizedStringR\x05label\x123\n" +
	"\aoptions\x18\x05 \x03(\v2\x19.category.AttributeOptionR\aoptions\x12\x1f\n" +
	"\vis_required\x18\x06 \x01(\bR\n" +
	"isRequired\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\"\xcf\x02\n" +
	"\x1eUpdateCategoryAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x01R\x04type\x88\x01\x01\x124\n" +
	"\x05label\x18\x04 \x01(\v2\x19.category.LocalizedStringH\x02R\x05label\x88\x01\x01\x123\n" +
	"\aoptions\x18\x05 \x03(\v2\x19.category.AttributeOptionR\aoptions\x12$\n" +
	"\vis_required\x18\x06 \x01(\bH\x03R\n" +
	"isRequired\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05H\x04R\tsortOrder\x88\x01\x01B\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_typeB\b\n" +
	"\x06_labelB\x0e\n" +
	"\f_is_requiredB\r\n" +
	"\v_sort_order\"0\n" +
	"\x1eDeleteCategoryAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\xe9\a\n" +
	"\x0fCategoryService\x12S\n" +
	"\x0eListCategories\x12\x1f.category.ListCategoriesRequest\x1a .category.ListCategoriesResponse\x12[\n" +
	"\x12ListFlatCategories\x12\x1f.category.ListCategoriesRequest\x1a$.category.ListFlatCategoriesResponse\x12G\n" +
	"\vGetCategory\x12\x1c.category.GetCategoryRequest\x1a\x1a.category.CategoryResponse\x12M\n" +
	"\x0eCreateCategory\x12\x1f.category.CreateCategoryRequest\x1a\x1a.category.CategoryResponse\x12M\n" +
	"\x0eUpdateCategory\x12\x1f.category.UpdateCategoryRequest\x1a\x1a.category.CategoryResponse\x12B\n" +
	"\x0eDeleteCategory\x12\x1f.category.DeleteCategoryRequest\x1a\x0f.category.Empty\x12k\n" +
	"\x16ListCategoryAttributes\x12'.category.ListCategoryAttributesRequest\x1a(.category.ListCategoryAttributesResponse\x12b\n" +
	"\x14GetCategoryAttribute\x12%.category.GetCategoryAttributeRequest\x1a#.category.CategoryAttributeResponse\x12h\n" +
	"\x17CreateCategoryAttribute\x12(.category.CreateCategoryAttributeRequest\x1a#.category.CategoryAttributeResponse\x12h\n" +
	"\x17UpdateCategoryAttribute\x12(.category.UpdateCategoryAttributeRequest\x1a#.category.CategoryAttributeResponse\x12T\n" +
	"\x17DeleteCategoryAttribute\x12(.category.DeleteCategoryAttributeRequest\x1a\x0f.category.EmptyB\x1cZ\x1amebellar-backend/pkg/pb;pbb\x06proto3"

var (
	file_category_proto_rawDescOnce sync.Once
	file_category_proto_rawDescData []byte
)

func file_category_proto_rawDescGZIP() []byte {
	file_category_proto_rawDescOnce.Do(func() {
		file_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_proto_rawDesc), len(file_category_proto_rawDesc)))
	})
	return file_category_proto_rawDescData
}

var file_category_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_category_proto_goTypes = []any{
	(*LocalizedString)(nil),                // 0: category.LocalizedString
	(*AttributeOption)(nil),                // 1: category.AttributeOption
	(*CategoryAttribute)(nil),              // 2: category.CategoryAttribute
	(*Category)(nil),                       // 3: category.Category
	(*FlatCategory)(nil),                   // 4: category.FlatCategory
	(*ListCategoriesRequest)(nil),          // 5: category.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),         // 6: category.ListCategoriesResponse
	(*ListFlatCategoriesResponse)(nil),     // 7: category.ListFlatCategoriesResponse
	(*GetCategoryRequest)(nil),             // 8: category.GetCategoryRequest
	(*CategoryResponse)(nil),               // 9: category.CategoryResponse
	(*CreateCategoryRequest)(nil),          // 10: category.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),          // 11: category.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),          // 12: category.DeleteCategoryRequest
	(*ListCategoryAttributesRequest)(nil),  // 13: category.ListCategoryAttributesRequest
	(*ListCategoryAttributesResponse)(nil), // 14: category.ListCategoryAttributesResponse
	(*GetCategoryAttributeRequest)(nil),    // 15: category.GetCategoryAttributeRequest
	(*CategoryAttributeResponse)(nil),      // 16: category.CategoryAttributeResponse
	(*CreateCategoryAttributeRequest)(nil), // 17: category.CreateCategoryAttributeRequest
	(*UpdateCategoryAttributeRequest)(nil), // 18: category.UpdateCategoryAttributeRequest
	(*DeleteCategoryAttributeRequest)(nil), // 19: category.DeleteCategoryAttributeRequest
	(*Empty)(nil),                          // 20: category.Empty
	(*timestamppb.Timestamp)(nil),          // 21: google.protobuf.Timestamp
}
var file_category_proto_depIdxs = []int32{
	0,  // 0: category.AttributeOption.label:type_name -> category.LocalizedString
	0,  // 1: category.CategoryAttribute.label:type_name -> category.LocalizedString
	1,  // 2: category.CategoryAttribute.options:type_name -> category.AttributeOption
	21, // 3: category.CategoryAttribute.created_at:type_name -> google.protobuf.Timestamp
	21, // 4: category.CategoryAttribute.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: category.Category.name:type_name -> category.LocalizedString
	3,  // 6: category.Category.sub_categories:type_name -> category.Category
	2,  // 7: category.Category.attributes:type_name -> category.CategoryAttribute
	0,  // 8: category.FlatCategory.name:type_name -> category.LocalizedString
	3,  // 9: category.ListCategoriesResponse.categories:type_name -> category.Category
	4,  // 10: category.ListFlatCategoriesResponse.categories:type_name -> category.FlatCategory
	3,  // 11: category.CategoryResponse.category:type_name -> category.Category
	0,  // 12: category.CreateCategoryRequest.name:type_name -> category.LocalizedString
	0,  // 13: category.UpdateCategoryRequest.name:type_name -> category.LocalizedString
	2,  // 14: category.ListCategoryAttributesResponse.attributes:type_name -> category.CategoryAttribute
	2,  // 15: category.CategoryAttributeResponse.attribute:type_name -> category.CategoryAttribute
	0,  // 16: category.CreateCategoryAttributeRequest.label:type_name -> category.LocalizedString
	1,  // 17: category.CreateCategoryAttributeRequest.options:type_name -> category.AttributeOption
	0,  // 18: category.UpdateCategoryAttributeRequest.label:type_name -> category.LocalizedString
	1,  // 19: category.UpdateCategoryAttributeRequest.options:type_name -> category.AttributeOption
	5,  // 20: category.CategoryService.ListCategories:input_type -> category.ListCategoriesRequest
	5,  // 21: category.CategoryService.ListFlatCategories:input_type -> category.ListCategoriesRequest
	8,  // 22: category.CategoryService.GetCategory:input_type -> category.GetCategoryRequest
	10, // 23: category.CategoryService.CreateCategory:input_type -> category.CreateCategoryRequest
	11, // 24: category.CategoryService.UpdateCategory:input_type -> category.UpdateCategoryRequest
	12, // 25: category.CategoryService.DeleteCategory:input_type -> category.DeleteCategoryRequest
	13, // 26: category.CategoryService.ListCategoryAttributes:input_type -> category.ListCategoryAttributesRequest
	15, // 27: category.CategoryService.GetCategoryAttribute:input_type -> category.GetCategoryAttributeRequest
	17, // 28: category.CategoryService.CreateCategoryAttribute:input_type -> category.CreateCategoryAttributeRequest
	18, // 29: category.CategoryService.UpdateCategoryAttribute:input_type -> category.UpdateCategoryAttributeRequest
	19, // 30: category.CategoryService.DeleteCategoryAttribute:input_type -> category.DeleteCategoryAttributeRequest
	6,  // 31: category.CategoryService.ListCategories:output_type -> category.ListCategoriesResponse
	7,  // 32: category.CategoryService.ListFlatCategories:output_type -> category.ListFlatCategoriesResponse
	9,  // 33: category.CategoryService.GetCategory:output_type -> category.CategoryResponse
	9,  // 34: category.CategoryService.CreateCategory:output_type -> category.CategoryResponse
	9,  // 35: category.CategoryService.UpdateCategory:output_type -> category.CategoryResponse
	20, // 36: category.CategoryService.DeleteCategory:output_type -> category.Empty
	14, // 37: category.CategoryService.ListCategoryAttributes:output_type -> category.ListCategoryAttributesResponse
	16, // 38: category.CategoryService.GetCategoryAttribute:output_type -> category.CategoryAttributeResponse
	16, // 39: category.CategoryService.CreateCategoryAttribute:output_type -> category.CategoryAttributeResponse
	16, // 40: category.CategoryService.UpdateCategoryAttribute:output_type -> category.CategoryAttributeResponse
	20, // 41: category.CategoryService.DeleteCategoryAttribute:output_type -> category.Empty
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_category_proto_init() }
func file_category_proto_init() {
	if File_category_proto != nil {
		return
	}
	file_category_proto_msgTypes[11].OneofWrappers = []any{}
	file_category_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_proto_rawDesc), len(file_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_proto_goTypes,
		DependencyIndexes: file_category_proto_depIdxs,
		MessageInfos:      file_category_proto_msgTypes,
	}.Build()
	File_category_proto = out.File
	file_category_proto_goTypes = nil
	file_category_proto_depIdxs = nil
}
