// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LocalizedString - Multi-language text (uz, ru, en)
type LocalizedString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uz            string                 `protobuf:"bytes,1,opt,name=uz,proto3" json:"uz,omitempty"`
	Ru            string                 `protobuf:"bytes,2,opt,name=ru,proto3" json:"ru,omitempty"`
	En            string                 `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedString) Reset() {
	*x = LocalizedString{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedString) ProtoMessage() {}

func (x *LocalizedString) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedString.ProtoReflect.Descriptor instead.
func (*LocalizedString) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *LocalizedString) GetUz() string {
	if x != nil {
		return x.Uz
	}
	return ""
}

func (x *LocalizedString) GetRu() string {
	if x != nil {
		return x.Ru
	}
	return ""
}

func (x *LocalizedString) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

// Pagination request/response helpers
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Empty message for RPCs that don't need a request/response
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // Legacy plain string
	NameLocalized *LocalizedString       `protobuf:"bytes,3,opt,name=name_localized,json=nameLocalized,proto3" json:"name_localized,omitempty"` // Multi-language
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                                        // ISO 3166-2 code (e.g., UZ-TK)
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Ordering      int32                  `protobuf:"varint,6,opt,name=ordering,proto3" json:"ordering,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Region) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Region) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Region) GetNameLocalized() *LocalizedString {
	if x != nil {
		return x.NameLocalized
	}
	return nil
}

func (x *Region) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Region) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Region) GetOrdering() int32 {
	if x != nil {
		return x.Ordering
	}
	return 0
}

func (x *Region) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Region) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsRequest) Reset() {
	*x = ListRegionsRequest{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsRequest) ProtoMessage() {}

func (x *ListRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsRequest.ProtoReflect.Descriptor instead.
func (*ListRegionsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *ListRegionsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsResponse) Reset() {
	*x = ListRegionsResponse{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsResponse) ProtoMessage() {}

func (x *ListRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsResponse.ProtoReflect.Descriptor instead.
func (*ListRegionsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *ListRegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *ListRegionsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionRequest) Reset() {
	*x = GetRegionRequest{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionRequest) ProtoMessage() {}

func (x *GetRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionRequest.ProtoReflect.Descriptor instead.
func (*GetRegionRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *GetRegionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *LocalizedString       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Ordering      int32                  `protobuf:"varint,3,opt,name=ordering,proto3" json:"ordering,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionRequest) Reset() {
	*x = CreateRegionRequest{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionRequest) ProtoMessage() {}

func (x *CreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRegionRequest) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreateRegionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRegionRequest) GetOrdering() int32 {
	if x != nil {
		return x.Ordering
	}
	return 0
}

func (x *CreateRegionRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *LocalizedString       `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Code          *string                `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Ordering      *int32                 `protobuf:"varint,4,opt,name=ordering,proto3,oneof" json:"ordering,omitempty"`
	IsActive      *bool                  `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegionRequest) Reset() {
	*x = UpdateRegionRequest{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegionRequest) ProtoMessage() {}

func (x *UpdateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegionRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegionRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRegionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRegionRequest) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateRegionRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *UpdateRegionRequest) GetOrdering() int32 {
	if x != nil && x.Ordering != nil {
		return *x.Ordering
	}
	return 0
}

func (x *UpdateRegionRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type RegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *Region                `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionResponse) Reset() {
	*x = RegionResponse{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionResponse) ProtoMessage() {}

func (x *RegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionResponse.ProtoReflect.Descriptor instead.
func (*RegionResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *RegionResponse) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type DeleteRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRegionRequest) Reset() {
	*x = DeleteRegionRequest{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRegionRequest) ProtoMessage() {}

func (x *DeleteRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRegionRequest.ProtoReflect.Descriptor instead.
func (*DeleteRegionRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRegionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *LocalizedString       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *LocalizedString       `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // none, category, product, external
	TargetId      string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *Banner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Banner) GetTitle() *LocalizedString {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Banner) GetSubtitle() *LocalizedString {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *Banner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Banner) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *Banner) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Banner) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Banner) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Banner) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListBannersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBannersRequest) Reset() {
	*x = ListBannersRequest{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBannersRequest) ProtoMessage() {}

func (x *ListBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBannersRequest.ProtoReflect.Descriptor instead.
func (*ListBannersRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *ListBannersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListBannersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banners       []*Banner              `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBannersResponse) Reset() {
	*x = ListBannersResponse{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBannersResponse) ProtoMessage() {}

func (x *ListBannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBannersResponse.ProtoReflect.Descriptor instead.
func (*ListBannersResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *ListBannersResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *ListBannersResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerRequest) Reset() {
	*x = GetBannerRequest{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerRequest) ProtoMessage() {}

func (x *GetBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerRequest.ProtoReflect.Descriptor instead.
func (*GetBannerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *GetBannerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *LocalizedString       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *LocalizedString       `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBannerRequest) Reset() {
	*x = CreateBannerRequest{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerRequest) ProtoMessage() {}

func (x *CreateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *CreateBannerRequest) GetTitle() *LocalizedString {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *CreateBannerRequest) GetSubtitle() *LocalizedString {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *CreateBannerRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateBannerRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CreateBannerRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CreateBannerRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateBannerRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *LocalizedString       `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Subtitle      *LocalizedString       `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	TargetType    *string                `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3,oneof" json:"target_type,omitempty"`
	TargetId      *string                `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	IsActive      *bool                  `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBannerRequest) Reset() {
	*x = UpdateBannerRequest{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerRequest) ProtoMessage() {}

func (x *UpdateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBannerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateBannerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBannerRequest) GetTitle() *LocalizedString {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateBannerRequest) GetSubtitle() *LocalizedString {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *UpdateBannerRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *UpdateBannerRequest) GetTargetType() string {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return ""
}

func (x *UpdateBannerRequest) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *UpdateBannerRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

func (x *UpdateBannerRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type BannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banner        *Banner                `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *BannerResponse) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

type DeleteBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBannerRequest) Reset() {
	*x = DeleteBannerRequest{}
	mi := &file_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerRequest) ProtoMessage() {}

func (x *DeleteBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteBannerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancellationReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          *LocalizedString       `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancellationReason) Reset() {
	*x = CancellationReason{}
	mi := &file_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancellationReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancellationReason) ProtoMessage() {}

func (x *CancellationReason) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancellationReason.ProtoReflect.Descriptor instead.
func (*CancellationReason) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{20}
}

func (x *CancellationReason) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancellationReason) GetText() *LocalizedString {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *CancellationReason) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListCancellationReasonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCancellationReasonsRequest) Reset() {
	*x = ListCancellationReasonsRequest{}
	mi := &file_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCancellationReasonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCancellationReasonsRequest) ProtoMessage() {}

func (x *ListCancellationReasonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCancellationReasonsRequest.ProtoReflect.Descriptor instead.
func (*ListCancellationReasonsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{21}
}

type ListCancellationReasonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reasons       []*CancellationReason  `protobuf:"bytes,1,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCancellationReasonsResponse) Reset() {
	*x = ListCancellationReasonsResponse{}
	mi := &file_common_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCancellationReasonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCancellationReasonsResponse) ProtoMessage() {}

func (x *ListCancellationReasonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCancellationReasonsResponse.ProtoReflect.Descriptor instead.
func (*ListCancellationReasonsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{22}
}

func (x *ListCancellationReasonsResponse) GetReasons() []*CancellationReason {
	if x != nil {
		return x.Reasons
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x0fLocalizedString\x12\x0e\n" +
	"\x02uz\x18\x01 \x01(\tR\x02uz\x12\x0e\n" +
	"\x02ru\x18\x02 \x01(\tR\x02ru\x12\x0e\n" +
	"\x02en\x18\x03 \x01(\tR\x02en\"=\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"u\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\a\n" +
	"\x05Empty\"\xaf\x02\n" +
	"\x06Region\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\x0ename_localized\x18\x03 \x01(\v2\x17.common.LocalizedStringR\rnameLocalized\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1a\n" +
	"\bordering\x18\x06 \x01(\x05R\bordering\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"5\n" +
	"\x12ListRegionsRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"U\n" +
	"\x13ListRegionsResponse\x12(\n" +
	"\aregions\x18\x01 \x03(\v2\x0e.common.RegionR\aregions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\"\n" +
	"\x10GetRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x8f\x01\n" +
	"\x13CreateRegionRequest\x12+\n" +
	"\x04name\x18\x01 \x01(\v2\x17.common.LocalizedStringR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bordering\x18\x03 \x01(\x05R\bordering\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\xe0\x01\n" +
	"\x13UpdateRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x17.common.LocalizedStringH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x03 \x01(\tH\x01R\x04code\x88\x01\x01\x12\x1f\n" +
	"\bordering\x18\x04 \x01(\x05H\x02R\bordering\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x05 \x01(\bH\x03R\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_codeB\v\n" +
	"\t_orderingB\f\n" +
	"\n" +
	"_is_active\"8\n" +
	"\x0eRegionResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.common.RegionR\x06region\"%\n" +
	"\x13DeleteRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xce\x02\n" +
	"\x06Banner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05title\x18\x02 \x01(\v2\x17.common.LocalizedStringR\x05title\x123\n" +
	"\bsubtitle\x18\x03 \x01(\v2\x17.common.LocalizedStringR\bsubtitle\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x12ListBannersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"U\n" +
	"\x13ListBannersResponse\x12(\n" +
	"\abanners\x18\x01 \x03(\v2\x0e.common.BannerR\abanners\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\"\n" +
	"\x10GetBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x02\n" +
	"\x13CreateBannerRequest\x12-\n" +
	"\x05title\x18\x01 \x01(\v2\x17.common.LocalizedStringR\x05title\x123\n" +
	"\bsubtitle\x18\x02 \x01(\v2\x17.common.LocalizedStringR\bsubtitle\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\xa3\x03\n" +
	"\x13UpdateBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x05title\x18\x02 \x01(\v2\x17.common.LocalizedStringH\x00R\x05title\x88\x01\x01\x128\n" +
	"\bsubtitle\x18\x03 \x01(\v2\x17.common.LocalizedStringH\x01R\bsubtitle\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x04 \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12$\n" +
	"\vtarget_type\x18\x05 \x01(\tH\x03R\n" +
	"targetType\x88\x01\x01\x12 \n" +
	"\ttarget_id\x18\x06 \x01(\tH\x04R\btargetId\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05H\x05R\tsortOrder\x88\x01\x01\x12 \n" +
	"\tis_active\x18\b \x01(\bH\x06R\bisActive\x88\x01\x01B\b\n" +
	"\x06_titleB\v\n" +
	"\t_subtitleB\f\n" +
	"\n" +
	"_image_urlB\x0e\n" +
	"\f_target_typeB\f\n" +
	"\n" +
	"_target_idB\r\n" +
	"\v_sort_orderB\f\n" +
	"\n" +
	"_is_active\"8\n" +
	"\x0eBannerResponse\x12&\n" +
	"\x06banner\x18\x01 \x01(\v2\x0e.common.BannerR\x06banner\"%\n" +
	"\x13DeleteBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x12CancellationReason\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04text\x18\x02 \x01(\v2\x17.common.LocalizedStringR\x04text\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\" \n" +
	"\x1eListCancellationReasonsRequest\"W\n" +
	"\x1fListCancellationReasonsResponse\x124\n" +
	"\areasons\x18\x01 \x03(\v2\x1a.common.CancellationReasonR\areasons2\x95\x06\n" +
	"\rCommonService\x12F\n" +
	"\vListRegions\x12\x1a.common.ListRegionsRequest\x1a\x1b.common.ListRegionsResponse\x12=\n" +
	"\tGetRegion\x12\x18.common.GetRegionRequest\x1a\x16.common.RegionResponse\x12C\n" +
	"\fCreateRegion\x12\x1b.common.CreateRegionRequest\x1a\x16.common.RegionResponse\x12C\n" +
	"\fUpdateRegion\x12\x1b.common.UpdateRegionRequest\x1a\x16.common.RegionResponse\x12:\n" +
	"\fDeleteRegion\x12\x1b.common.DeleteRegionRequest\x1a\r.common.Empty\x12F\n" +
	"\vListBanners\x12\x1a.common.ListBannersRequest\x1a\x1b.common.ListBannersResponse\x12=\n" +
	"\tGetBanner\x12\x18.common.GetBannerRequest\x1a\x16.common.BannerResponse\x12C\n" +
	"\fCreateBanner\x12\x1b.common.CreateBannerRequest\x1a\x16.common.BannerResponse\x12C\n" +
	"\fUpdateBanner\x12\x1b.common.UpdateBannerRequest\x1a\x16.common.BannerResponse\x12:\n" +
	"\fDeleteBanner\x12\x1b.common.DeleteBannerRequest\x1a\r.common.Empty\x12j\n" +
	"\x17ListCancellationReasons\x12&.common.ListCancellationReasonsRequest\x1a'.common.ListCancellationReasonsResponseB\x1cZ\x1amebellar-backend/pkg/pb;pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_common_proto_goTypes = []any{
	(*LocalizedString)(nil),                 // 0: common.LocalizedString
	(*PaginationRequest)(nil),               // 1: common.PaginationRequest
	(*PaginationResponse)(nil),              // 2: common.PaginationResponse
	(*Empty)(nil),                           // 3: common.Empty
	(*Region)(nil),                          // 4: common.Region
	(*ListRegionsRequest)(nil),              // 5: common.ListRegionsRequest
	(*ListRegionsResponse)(nil),             // 6: common.ListRegionsResponse
	(*GetRegionRequest)(nil),                // 7: common.GetRegionRequest
	(*CreateRegionRequest)(nil),             // 8: common.CreateRegionRequest
	(*UpdateRegionRequest)(nil),             // 9: common.UpdateRegionRequest
	(*RegionResponse)(nil),                  // 10: common.RegionResponse
	(*DeleteRegionRequest)(nil),             // 11: common.DeleteRegionRequest
	(*Banner)(nil),                          // 12: common.Banner
	(*ListBannersRequest)(nil),              // 13: common.ListBannersRequest
	(*ListBannersResponse)(nil),             // 14: common.ListBannersResponse
	(*GetBannerRequest)(nil),                // 15: common.GetBannerRequest
	(*CreateBannerRequest)(nil),             // 16: common.CreateBannerRequest
	(*UpdateBannerRequest)(nil),             // 17: common.UpdateBannerRequest
	(*BannerResponse)(nil),                  // 18: common.BannerResponse
	(*DeleteBannerRequest)(nil),             // 19: common.DeleteBannerRequest
	(*CancellationReason)(nil),              // 20: common.CancellationReason
	(*ListCancellationReasonsRequest)(nil),  // 21: common.ListCancellationReasonsRequest
	(*ListCancellationReasonsResponse)(nil), // 22: common.ListCancellationReasonsResponse
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: common.Region.name_localized:type_name -> common.LocalizedString
	23, // 1: common.Region.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: common.Region.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 3: common.ListRegionsResponse.regions:type_name -> common.Region
	0,  // 4: common.CreateRegionRequest.name:type_name -> common.LocalizedString
	0,  // 5: common.UpdateRegionRequest.name:type_name -> common.LocalizedString
	4,  // 6: common.RegionResponse.region:type_name -> common.Region
	0,  // 7: common.Banner.title:type_name -> common.LocalizedString
	0,  // 8: common.Banner.subtitle:type_name -> common.LocalizedString
	23, // 9: common.Banner.created_at:type_name -> google.protobuf.Timestamp
	12, // 10: common.ListBannersResponse.banners:type_name -> common.Banner
	0,  // 11: common.CreateBannerRequest.title:type_name -> common.LocalizedString
	0,  // 12: common.CreateBannerRequest.subtitle:type_name -> common.LocalizedString
	0,  // 13: common.UpdateBannerRequest.title:type_name -> common.LocalizedString
	0,  // 14: common.UpdateBannerRequest.subtitle:type_name -> common.LocalizedString
	12, // 15: common.BannerResponse.banner:type_name -> common.Banner
	0,  // 16: common.CancellationReason.text:type_name -> common.LocalizedString
	20, // 17: common.ListCancellationReasonsResponse.reasons:type_name -> common.CancellationReason
	5,  // 18: common.CommonService.ListRegions:input_type -> common.ListRegionsRequest
	7,  // 19: common.CommonService.GetRegion:input_type -> common.GetRegionRequest
	8,  // 20: common.CommonService.CreateRegion:input_type -> common.CreateRegionRequest
	9,  // 21: common.CommonService.UpdateRegion:input_type -> common.UpdateRegionRequest
	11, // 22: common.CommonService.DeleteRegion:input_type -> common.DeleteRegionRequest
	13, // 23: common.CommonService.ListBanners:input_type -> common.ListBannersRequest
	15, // 24: common.CommonService.GetBanner:input_type -> common.GetBannerRequest
	16, // 25: common.CommonService.CreateBanner:input_type -> common.CreateBannerRequest
	17, // 26: common.CommonService.UpdateBanner:input_type -> common.UpdateBannerRequest
	19, // 27: common.CommonService.DeleteBanner:input_type -> common.DeleteBannerRequest
	21, // 28: common.CommonService.ListCancellationReasons:input_type -> common.ListCancellationReasonsRequest
	6,  // 29: common.CommonService.ListRegions:output_type -> common.ListRegionsResponse
	10, // 30: common.CommonService.GetRegion:output_type -> common.RegionResponse
	10, // 31: common.CommonService.CreateRegion:output_type -> common.RegionResponse
	10, // 32: common.CommonService.UpdateRegion:output_type -> common.RegionResponse
	3,  // 33: common.CommonService.DeleteRegion:output_type -> common.Empty
	14, // 34: common.CommonService.ListBanners:output_type -> common.ListBannersResponse
	18, // 35: common.CommonService.GetBanner:output_type -> common.BannerResponse
	18, // 36: common.CommonService.CreateBanner:output_type -> common.BannerResponse
	18, // 37: common.CommonService.UpdateBanner:output_type -> common.BannerResponse
	3,  // 38: common.CommonService.DeleteBanner:output_type -> common.Empty
	22, // 39: common.CommonService.ListCancellationReasons:output_type -> common.ListCancellationReasonsResponse
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[9].OneofWrappers = []any{}
	file_common_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
