// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_NEW         OrderStatus = 1
	OrderStatus_ORDER_STATUS_CONFIRMED   OrderStatus = 2
	OrderStatus_ORDER_STATUS_SHIPPING    OrderStatus = 3
	OrderStatus_ORDER_STATUS_COMPLETED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_NEW",
		2: "ORDER_STATUS_CONFIRMED",
		3: "ORDER_STATUS_SHIPPING",
		4: "ORDER_STATUS_COMPLETED",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_NEW":         1,
		"ORDER_STATUS_CONFIRMED":   2,
		"ORDER_STATUS_SHIPPING":    3,
		"ORDER_STATUS_COMPLETED":   4,
		"ORDER_STATUS_CANCELLED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type OrderEventType int32

const (
	OrderEventType_ORDER_EVENT_TYPE_UNSPECIFIED    OrderEventType = 0
	OrderEventType_ORDER_EVENT_TYPE_CREATED        OrderEventType = 1
	OrderEventType_ORDER_EVENT_TYPE_UPDATED        OrderEventType = 2
	OrderEventType_ORDER_EVENT_TYPE_STATUS_CHANGED OrderEventType = 3
	OrderEventType_ORDER_EVENT_TYPE_DELETED        OrderEventType = 4
)

// Enum value maps for OrderEventType.
var (
	OrderEventType_name = map[int32]string{
		0: "ORDER_EVENT_TYPE_UNSPECIFIED",
		1: "ORDER_EVENT_TYPE_CREATED",
		2: "ORDER_EVENT_TYPE_UPDATED",
		3: "ORDER_EVENT_TYPE_STATUS_CHANGED",
		4: "ORDER_EVENT_TYPE_DELETED",
	}
	OrderEventType_value = map[string]int32{
		"ORDER_EVENT_TYPE_UNSPECIFIED":    0,
		"ORDER_EVENT_TYPE_CREATED":        1,
		"ORDER_EVENT_TYPE_UPDATED":        2,
		"ORDER_EVENT_TYPE_STATUS_CHANGED": 3,
		"ORDER_EVENT_TYPE_DELETED":        4,
	}
)

func (x OrderEventType) Enum() *OrderEventType {
	p := new(OrderEventType)
	*p = x
	return p
}

func (x OrderEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (OrderEventType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x OrderEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderEventType.Descriptor instead.
func (OrderEventType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage  string                 `protobuf:"bytes,5,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName      string                 `protobuf:"bytes,3,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,5,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	ClientAddress string                 `protobuf:"bytes,6,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DeliveryPrice float64                `protobuf:"fixed64,8,opt,name=delivery_price,json=deliveryPrice,proto3" json:"delivery_price,omitempty"`
	Status        OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	ClientNote    string                 `protobuf:"bytes,10,opt,name=client_note,json=clientNote,proto3" json:"client_note,omitempty"`
	SellerNote    string                 `protobuf:"bytes,11,opt,name=seller_note,json=sellerNote,proto3" json:"seller_note,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	ItemsCount    int32                  `protobuf:"varint,13,opt,name=items_count,json=itemsCount,proto3" json:"items_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Order) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *Order) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Order) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *Order) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetDeliveryPrice() float64 {
	if x != nil {
		return x.DeliveryPrice
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetClientNote() string {
	if x != nil {
		return x.ClientNote
	}
	return ""
}

func (x *Order) GetSellerNote() string {
	if x != nil {
		return x.SellerNote
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetItemsCount() int32 {
	if x != nil {
		return x.ItemsCount
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type OrderItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage  string                 `protobuf:"bytes,3,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemInput) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemInput) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItemInput) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *OrderItemInput) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemInput) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientPhone   string                 `protobuf:"bytes,3,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	ClientAddress string                 `protobuf:"bytes,4,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DeliveryPrice float64                `protobuf:"fixed64,6,opt,name=delivery_price,json=deliveryPrice,proto3" json:"delivery_price,omitempty"`
	ClientNote    string                 `protobuf:"bytes,7,opt,name=client_note,json=clientNote,proto3" json:"client_note,omitempty"`
	Items         []*OrderItemInput      `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *CreateOrderRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateOrderRequest) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *CreateOrderRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetDeliveryPrice() float64 {
	if x != nil {
		return x.DeliveryPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetClientNote() string {
	if x != nil {
		return x.ClientNote
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	SellerNote    string                 `protobuf:"bytes,3,opt,name=seller_note,json=sellerNote,proto3" json:"seller_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrderStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderStatusRequest) GetSellerNote() string {
	if x != nil {
		return x.SellerNote
	}
	return ""
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Statuses      []OrderStatus          `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=order.OrderStatus" json:"statuses,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatuses() []OrderStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

type StreamOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Statuses      []OrderStatus          `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=order.OrderStatus" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrdersRequest) Reset() {
	*x = StreamOrdersRequest{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrdersRequest) ProtoMessage() {}

func (x *StreamOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrdersRequest.ProtoReflect.Descriptor instead.
func (*StreamOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *StreamOrdersRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *StreamOrdersRequest) GetStatuses() []OrderStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OrderEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=order.OrderEventType" json:"type,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *OrderEvent) GetType() OrderEventType {
	if x != nil {
		return x.Type
	}
	return OrderEventType_ORDER_EVENT_TYPE_UNSPECIFIED
}

func (x *OrderEvent) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_image\x18\x05 \x01(\tR\fproductImage\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xee\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1b\n" +
	"\tshop_name\x18\x03 \x01(\tR\bshopName\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_phone\x18\x05 \x01(\tR\vclientPhone\x12%\n" +
	"\x0eclient_address\x18\x06 \x01(\tR\rclientAddress\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x01R\vtotalAmount\x12%\n" +
	"\x0edelivery_price\x18\b \x01(\x01R\rdeliveryPrice\x12*\n" +
	"\x06status\x18\t \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1f\n" +
	"\vclient_note\x18\n" +
	" \x01(\tR\n" +
	"clientNote\x12\x1f\n" +
	"\vseller_note\x18\v \x01(\tR\n" +
	"sellerNote\x12&\n" +
	"\x05items\x18\f \x03(\v2\x10.order.OrderItemR\x05items\x12\x1f\n" +
	"\vitems_count\x18\r \x01(\x05R\n" +
	"itemsCount\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa9\x01\n" +
	"\x0eOrderItemInput\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_image\x18\x03 \x01(\tR\fproductImage\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\xb0\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_phone\x18\x03 \x01(\tR\vclientPhone\x12%\n" +
	"\x0eclient_address\x18\x04 \x01(\tR\rclientAddress\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12%\n" +
	"\x0edelivery_price\x18\x06 \x01(\x01R\rdeliveryPrice\x12\x1f\n" +
	"\vclient_note\x18\a \x01(\tR\n" +
	"clientNote\x12+\n" +
	"\x05items\x18\b \x03(\v2\x15.order.OrderItemInputR\x05items\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1f\n" +
	"\vseller_note\x18\x03 \x01(\tR\n" +
	"sellerNote\"$\n" +
	"\x12DeleteOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x86\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12.\n" +
	"\bstatuses\x18\x02 \x03(\x0e2\x12.order.OrderStatusR\bstatuses\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"z\n" +
	"\x12ListOrdersResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"3\n" +
	"\rOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"\a\n" +
	"\x05Empty\"^\n" +
	"\x13StreamOrdersRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12.\n" +
	"\bstatuses\x18\x02 \x03(\x0e2\x12.order.OrderStatusR\bstatuses\"[\n" +
	"\n" +
	"OrderEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.order.OrderEventTypeR\x04type\x12\"\n" +
	"\x05order\x18\x02 \x01(\v2\f.order.OrderR\x05order*\xb0\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_STATUS_NEW\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CONFIRMED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_SHIPPING\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05*\xb1\x01\n" +
	"\x0eOrderEventType\x12 \n" +
	"\x1cORDER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ORDER_EVENT_TYPE_CREATED\x10\x01\x12\x1c\n" +
	"\x18ORDER_EVENT_TYPE_UPDATED\x10\x02\x12#\n" +
	"\x1fORDER_EVENT_TYPE_STATUS_CHANGED\x10\x03\x12\x1c\n" +
	"\x18ORDER_EVENT_TYPE_DELETED\x10\x042\x90\x03\n" +
	"\fOrderService\x12>\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x14.order.OrderResponse\x128\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x14.order.OrderResponse\x12J\n" +
	"\x11UpdateOrderStatus\x12\x1f.order.UpdateOrderStatusRequest\x1a\x14.order.OrderResponse\x126\n" +
	"\vDeleteOrder\x12\x19.order.DeleteOrderRequest\x1a\f.order.Empty\x12A\n" +
	"\n" +
	"ListOrders\x12\x18.order.ListOrdersRequest\x1a\x19.order.ListOrdersResponse\x12?\n" +
	"\fStreamOrders\x12\x1a.order.StreamOrdersRequest\x1a\x11.order.OrderEvent0\x01B\x1cZ\x1amebellar-backend/pkg/pb;pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_order_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: order.OrderStatus
	(OrderEventType)(0),              // 1: order.OrderEventType
	(*OrderItem)(nil),                // 2: order.OrderItem
	(*Order)(nil),                    // 3: order.Order
	(*OrderItemInput)(nil),           // 4: order.OrderItemInput
	(*CreateOrderRequest)(nil),       // 5: order.CreateOrderRequest
	(*GetOrderRequest)(nil),          // 6: order.GetOrderRequest
	(*UpdateOrderStatusRequest)(nil), // 7: order.UpdateOrderStatusRequest
	(*DeleteOrderRequest)(nil),       // 8: order.DeleteOrderRequest
	(*ListOrdersRequest)(nil),        // 9: order.ListOrdersRequest
	(*ListOrdersResponse)(nil),       // 10: order.ListOrdersResponse
	(*OrderResponse)(nil),            // 11: order.OrderResponse
	(*Empty)(nil),                    // 12: order.Empty
	(*StreamOrdersRequest)(nil),      // 13: order.StreamOrdersRequest
	(*OrderEvent)(nil),               // 14: order.OrderEvent
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	15, // 0: order.OrderItem.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: order.Order.status:type_name -> order.OrderStatus
	2,  // 2: order.Order.items:type_name -> order.OrderItem
	15, // 3: order.Order.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: order.Order.updated_at:type_name -> google.protobuf.Timestamp
	15, // 5: order.Order.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 6: order.CreateOrderRequest.items:type_name -> order.OrderItemInput
	0,  // 7: order.UpdateOrderStatusRequest.status:type_name -> order.OrderStatus
	0,  // 8: order.ListOrdersRequest.statuses:type_name -> order.OrderStatus
	3,  // 9: order.ListOrdersResponse.orders:type_name -> order.Order
	3,  // 10: order.OrderResponse.order:type_name -> order.Order
	0,  // 11: order.StreamOrdersRequest.statuses:type_name -> order.OrderStatus
	1,  // 12: order.OrderEvent.type:type_name -> order.OrderEventType
	3,  // 13: order.OrderEvent.order:type_name -> order.Order
	5,  // 14: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	6,  // 15: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	7,  // 16: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateOrderStatusRequest
	8,  // 17: order.OrderService.DeleteOrder:input_type -> order.DeleteOrderRequest
	9,  // 18: order.OrderService.ListOrders:input_type -> order.ListOrdersRequest
	13, // 19: order.OrderService.StreamOrders:input_type -> order.StreamOrdersRequest
	11, // 20: order.OrderService.CreateOrder:output_type -> order.OrderResponse
	11, // 21: order.OrderService.GetOrder:output_type -> order.OrderResponse
	11, // 22: order.OrderService.UpdateOrderStatus:output_type -> order.OrderResponse
	12, // 23: order.OrderService.DeleteOrder:output_type -> order.Empty
	10, // 24: order.OrderService.ListOrders:output_type -> order.ListOrdersResponse
	14, // 25: order.OrderService.StreamOrders:output_type -> order.OrderEvent
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
