// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalizedString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uz            string                 `protobuf:"bytes,1,opt,name=uz,proto3" json:"uz,omitempty"`
	Ru            string                 `protobuf:"bytes,2,opt,name=ru,proto3" json:"ru,omitempty"`
	En            string                 `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedString) Reset() {
	*x = LocalizedString{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedString) ProtoMessage() {}

func (x *LocalizedString) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedString.ProtoReflect.Descriptor instead.
func (*LocalizedString) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *LocalizedString) GetUz() string {
	if x != nil {
		return x.Uz
	}
	return ""
}

func (x *LocalizedString) GetRu() string {
	if x != nil {
		return x.Ru
	}
	return ""
}

func (x *LocalizedString) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

type RegionalPriceGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionIds     []string               `protobuf:"bytes,1,rep,name=region_ids,json=regionIds,proto3" json:"region_ids,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DeliveryDays  string                 `protobuf:"bytes,4,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionalPriceGroup) Reset() {
	*x = RegionalPriceGroup{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionalPriceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionalPriceGroup) ProtoMessage() {}

func (x *RegionalPriceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionalPriceGroup.ProtoReflect.Descriptor instead.
func (*RegionalPriceGroup) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *RegionalPriceGroup) GetRegionIds() []string {
	if x != nil {
		return x.RegionIds
	}
	return nil
}

func (x *RegionalPriceGroup) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RegionalPriceGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegionalPriceGroup) GetDeliveryDays() string {
	if x != nil {
		return x.DeliveryDays
	}
	return ""
}

type DeliverySettings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasInstallation   bool                   `protobuf:"varint,1,opt,name=has_installation,json=hasInstallation,proto3" json:"has_installation,omitempty"`
	InstallationPrice float64                `protobuf:"fixed64,2,opt,name=installation_price,json=installationPrice,proto3" json:"installation_price,omitempty"`
	HomeRegionPrice   float64                `protobuf:"fixed64,3,opt,name=home_region_price,json=homeRegionPrice,proto3" json:"home_region_price,omitempty"`
	IsHomeRegionFree  bool                   `protobuf:"varint,4,opt,name=is_home_region_free,json=isHomeRegionFree,proto3" json:"is_home_region_free,omitempty"`
	HomeDeliveryDays  string                 `protobuf:"bytes,5,opt,name=home_delivery_days,json=homeDeliveryDays,proto3" json:"home_delivery_days,omitempty"`
	RegionalPrices    []*RegionalPriceGroup  `protobuf:"bytes,6,rep,name=regional_prices,json=regionalPrices,proto3" json:"regional_prices,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeliverySettings) Reset() {
	*x = DeliverySettings{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverySettings) ProtoMessage() {}

func (x *DeliverySettings) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverySettings.ProtoReflect.Descriptor instead.
func (*DeliverySettings) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverySettings) GetHasInstallation() bool {
	if x != nil {
		return x.HasInstallation
	}
	return false
}

func (x *DeliverySettings) GetInstallationPrice() float64 {
	if x != nil {
		return x.InstallationPrice
	}
	return 0
}

func (x *DeliverySettings) GetHomeRegionPrice() float64 {
	if x != nil {
		return x.HomeRegionPrice
	}
	return 0
}

func (x *DeliverySettings) GetIsHomeRegionFree() bool {
	if x != nil {
		return x.IsHomeRegionFree
	}
	return false
}

func (x *DeliverySettings) GetHomeDeliveryDays() string {
	if x != nil {
		return x.HomeDeliveryDays
	}
	return ""
}

func (x *DeliverySettings) GetRegionalPrices() []*RegionalPriceGroup {
	if x != nil {
		return x.RegionalPrices
	}
	return nil
}

type ProductVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PriceModifier float64                `protobuf:"fixed64,3,opt,name=price_modifier,json=priceModifier,proto3" json:"price_modifier,omitempty"` // Price adjustment for this variant
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"` // Dynamic attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductVariant) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProductVariant) GetPriceModifier() float64 {
	if x != nil {
		return x.PriceModifier
	}
	return 0
}

func (x *ProductVariant) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductVariant) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Product struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId           string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId       string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name             *LocalizedString       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description      *LocalizedString       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice    float64                `protobuf:"fixed64,7,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	Images           []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	Specs            *structpb.Struct       `protobuf:"bytes,9,opt,name=specs,proto3" json:"specs,omitempty"` // Dynamic specifications
	Variants         []*ProductVariant      `protobuf:"bytes,10,rep,name=variants,proto3" json:"variants,omitempty"`
	DeliverySettings *DeliverySettings      `protobuf:"bytes,11,opt,name=delivery_settings,json=deliverySettings,proto3" json:"delivery_settings,omitempty"`
	Rating           float64                `protobuf:"fixed64,12,opt,name=rating,proto3" json:"rating,omitempty"`
	ViewCount        int32                  `protobuf:"varint,13,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	SoldCount        int32                  `protobuf:"varint,14,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	IsNew            bool                   `protobuf:"varint,15,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsPopular        bool                   `protobuf:"varint,16,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	IsActive         bool                   `protobuf:"varint,17,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Computed fields
	DiscountPercent int32 `protobuf:"varint,19,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	HasDiscount     bool  `protobuf:"varint,20,opt,name=has_discount,json=hasDiscount,proto3" json:"has_discount,omitempty"`
	// Optional: shop info for list views
	ShopName      string `protobuf:"bytes,21,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopLogo      string `protobuf:"bytes,22,opt,name=shop_logo,json=shopLogo,proto3" json:"shop_logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Product) GetDescription() *LocalizedString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDiscountPrice() float64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetSpecs() *structpb.Struct {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *Product) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Product) GetDeliverySettings() *DeliverySettings {
	if x != nil {
		return x.DeliverySettings
	}
	return nil
}

func (x *Product) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Product) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *Product) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Product) GetIsPopular() bool {
	if x != nil {
		return x.IsPopular
	}
	return false
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetDiscountPercent() int32 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *Product) GetHasDiscount() bool {
	if x != nil {
		return x.HasDiscount
	}
	return false
}

func (x *Product) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *Product) GetShopLogo() string {
	if x != nil {
		return x.ShopLogo
	}
	return ""
}

// Filters for listing products
type ProductFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	IsNew         bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsPopular     bool                   `protobuf:"varint,4,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,6,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,7,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Search        string                 `protobuf:"bytes,8,opt,name=search,proto3" json:"search,omitempty"`               // Search in name/description
	SortBy        string                 `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // price_asc, price_desc, newest, popular
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFilters) Reset() {
	*x = ProductFilters{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFilters) ProtoMessage() {}

func (x *ProductFilters) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFilters.ProtoReflect.Descriptor instead.
func (*ProductFilters) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductFilters) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductFilters) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ProductFilters) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *ProductFilters) GetIsPopular() bool {
	if x != nil {
		return x.IsPopular
	}
	return false
}

func (x *ProductFilters) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductFilters) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProductFilters) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ProductFilters) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ProductFilters) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *ProductFilters        `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsRequest) GetFilters() *ProductFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncrementView bool                   `protobuf:"varint,2,opt,name=increment_view,json=incrementView,proto3" json:"increment_view,omitempty"` // Whether to increment view count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductRequest) GetIncrementView() bool {
	if x != nil {
		return x.IncrementView
	}
	return false
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ShopId           string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId       string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name             *LocalizedString       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      *LocalizedString       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice    float64                `protobuf:"fixed64,6,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	Images           []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Specs            *structpb.Struct       `protobuf:"bytes,8,opt,name=specs,proto3" json:"specs,omitempty"`
	Variants         []*ProductVariant      `protobuf:"bytes,9,rep,name=variants,proto3" json:"variants,omitempty"`
	DeliverySettings *DeliverySettings      `protobuf:"bytes,10,opt,name=delivery_settings,json=deliverySettings,proto3" json:"delivery_settings,omitempty"`
	IsNew            bool                   `protobuf:"varint,11,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsPopular        bool                   `protobuf:"varint,12,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	IsActive         bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *CreateProductRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductRequest) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreateProductRequest) GetDescription() *LocalizedString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetDiscountPrice() float64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *CreateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductRequest) GetSpecs() *structpb.Struct {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *CreateProductRequest) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *CreateProductRequest) GetDeliverySettings() *DeliverySettings {
	if x != nil {
		return x.DeliverySettings
	}
	return nil
}

func (x *CreateProductRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateProductRequest) GetIsPopular() bool {
	if x != nil {
		return x.IsPopular
	}
	return false
}

func (x *CreateProductRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId       *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Name             *LocalizedString       `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description      *LocalizedString       `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price            *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	DiscountPrice    *float64               `protobuf:"fixed64,6,opt,name=discount_price,json=discountPrice,proto3,oneof" json:"discount_price,omitempty"`
	Images           []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`     // Replaces all images
	Specs            *structpb.Struct       `protobuf:"bytes,8,opt,name=specs,proto3" json:"specs,omitempty"`       // Replaces all specs
	Variants         []*ProductVariant      `protobuf:"bytes,9,rep,name=variants,proto3" json:"variants,omitempty"` // Replaces all variants
	DeliverySettings *DeliverySettings      `protobuf:"bytes,10,opt,name=delivery_settings,json=deliverySettings,proto3,oneof" json:"delivery_settings,omitempty"`
	IsNew            *bool                  `protobuf:"varint,11,opt,name=is_new,json=isNew,proto3,oneof" json:"is_new,omitempty"`
	IsPopular        *bool                  `protobuf:"varint,12,opt,name=is_popular,json=isPopular,proto3,oneof" json:"is_popular,omitempty"`
	IsActive         *bool                  `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() *LocalizedString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateProductRequest) GetDescription() *LocalizedString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetDiscountPrice() float64 {
	if x != nil && x.DiscountPrice != nil {
		return *x.DiscountPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateProductRequest) GetSpecs() *structpb.Struct {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *UpdateProductRequest) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *UpdateProductRequest) GetDeliverySettings() *DeliverySettings {
	if x != nil {
		return x.DeliverySettings
	}
	return nil
}

func (x *UpdateProductRequest) GetIsNew() bool {
	if x != nil && x.IsNew != nil {
		return *x.IsNew
	}
	return false
}

func (x *UpdateProductRequest) GetIsPopular() bool {
	if x != nil && x.IsPopular != nil {
		return *x.IsPopular
	}
	return false
}

func (x *UpdateProductRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Toggle product status (active/inactive)
type ToggleProductStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleProductStatusRequest) Reset() {
	*x = ToggleProductStatusRequest{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleProductStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleProductStatusRequest) ProtoMessage() {}

func (x *ToggleProductStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleProductStatusRequest.ProtoReflect.Descriptor instead.
func (*ToggleProductStatusRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleProductStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToggleProductStatusRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadImageRequest_Metadata
	//	*UploadImageRequest_Chunk
	Data          isUploadImageRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *UploadImageRequest) GetData() isUploadImageRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetMetadata() *ImageMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadImageRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadImageRequest_Data interface {
	isUploadImageRequest_Data()
}

type UploadImageRequest_Metadata struct {
	Metadata *ImageMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadImageRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadImageRequest_Metadata) isUploadImageRequest_Data() {}

func (*UploadImageRequest_Chunk) isUploadImageRequest_Data() {}

type ImageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // image/jpeg, image/png, etc.
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`       // Optional: associate with product
	ShopId        string                 `protobuf:"bytes,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`                // Required for authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMetadata) Reset() {
	*x = ImageMetadata{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMetadata) ProtoMessage() {}

func (x *ImageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMetadata.ProtoReflect.Descriptor instead.
func (*ImageMetadata) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *ImageMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ImageMetadata) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ImageMetadata) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *UploadImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadImageResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UploadImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Bulk upload response
type BulkUploadImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,2,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUploadImagesResponse) Reset() {
	*x = BulkUploadImagesResponse{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUploadImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUploadImagesResponse) ProtoMessage() {}

func (x *BulkUploadImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUploadImagesResponse.ProtoReflect.Descriptor instead.
func (*BulkUploadImagesResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *BulkUploadImagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkUploadImagesResponse) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *BulkUploadImagesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListNewArrivalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNewArrivalsRequest) Reset() {
	*x = ListNewArrivalsRequest{}
	mi := &file_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNewArrivalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNewArrivalsRequest) ProtoMessage() {}

func (x *ListNewArrivalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNewArrivalsRequest.ProtoReflect.Descriptor instead.
func (*ListNewArrivalsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{18}
}

func (x *ListNewArrivalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNewArrivalsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type ListPopularProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopularProductsRequest) Reset() {
	*x = ListPopularProductsRequest{}
	mi := &file_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopularProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularProductsRequest) ProtoMessage() {}

func (x *ListPopularProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularProductsRequest.ProtoReflect.Descriptor instead.
func (*ListPopularProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{19}
}

func (x *ListPopularProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPopularProductsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type CategoryProductsGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  *LocalizedString       `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategorySlug  string                 `protobuf:"bytes,3,opt,name=category_slug,json=categorySlug,proto3" json:"category_slug,omitempty"`
	Products      []*Product             `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,6,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryProductsGroup) Reset() {
	*x = CategoryProductsGroup{}
	mi := &file_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryProductsGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryProductsGroup) ProtoMessage() {}

func (x *CategoryProductsGroup) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryProductsGroup.ProtoReflect.Descriptor instead.
func (*CategoryProductsGroup) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{20}
}

func (x *CategoryProductsGroup) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryProductsGroup) GetCategoryName() *LocalizedString {
	if x != nil {
		return x.CategoryName
	}
	return nil
}

func (x *CategoryProductsGroup) GetCategorySlug() string {
	if x != nil {
		return x.CategorySlug
	}
	return ""
}

func (x *CategoryProductsGroup) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *CategoryProductsGroup) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryProductsGroup) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListProductsGroupedBySubcategoryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ParentCategoryId    string                 `protobuf:"bytes,1,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	ProductsPerCategory int32                  `protobuf:"varint,2,opt,name=products_per_category,json=productsPerCategory,proto3" json:"products_per_category,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListProductsGroupedBySubcategoryRequest) Reset() {
	*x = ListProductsGroupedBySubcategoryRequest{}
	mi := &file_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsGroupedBySubcategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsGroupedBySubcategoryRequest) ProtoMessage() {}

func (x *ListProductsGroupedBySubcategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsGroupedBySubcategoryRequest.ProtoReflect.Descriptor instead.
func (*ListProductsGroupedBySubcategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{21}
}

func (x *ListProductsGroupedBySubcategoryRequest) GetParentCategoryId() string {
	if x != nil {
		return x.ParentCategoryId
	}
	return ""
}

func (x *ListProductsGroupedBySubcategoryRequest) GetProductsPerCategory() int32 {
	if x != nil {
		return x.ProductsPerCategory
	}
	return 0
}

type ListProductsGroupedBySubcategoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Groups        []*CategoryProductsGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Count         int32                    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsGroupedBySubcategoryResponse) Reset() {
	*x = ListProductsGroupedBySubcategoryResponse{}
	mi := &file_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsGroupedBySubcategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsGroupedBySubcategoryResponse) ProtoMessage() {}

func (x *ListProductsGroupedBySubcategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsGroupedBySubcategoryResponse.ProtoReflect.Descriptor instead.
func (*ListProductsGroupedBySubcategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{22}
}

func (x *ListProductsGroupedBySubcategoryResponse) GetGroups() []*CategoryProductsGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListProductsGroupedBySubcategoryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListSellerProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        string                 `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"` // From X-Shop-ID header or param
	Filters       *ProductFilters        `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSellerProductsRequest) Reset() {
	*x = ListSellerProductsRequest{}
	mi := &file_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSellerProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSellerProductsRequest) ProtoMessage() {}

func (x *ListSellerProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSellerProductsRequest.ProtoReflect.Descriptor instead.
func (*ListSellerProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{23}
}

func (x *ListSellerProductsRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ListSellerProductsRequest) GetFilters() *ProductFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListSellerProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSellerProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{24}
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"A\n" +
	"\x0fLocalizedString\x12\x0e\n" +
	"\x02uz\x18\x01 \x01(\tR\x02uz\x12\x0e\n" +
	"\x02ru\x18\x02 \x01(\tR\x02ru\x12\x0e\n" +
	"\x02en\x18\x03 \x01(\tR\x02en\"\x82\x01\n" +
	"\x12RegionalPriceGroup\x12\x1d\n" +
	"\n" +
	"region_ids\x18\x01 \x03(\tR\tregionIds\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rdelivery_days\x18\x04 \x01(\tR\fdeliveryDays\"\xbb\x02\n" +
	"\x10DeliverySettings\x12)\n" +
	"\x10has_installation\x18\x01 \x01(\bR\x0fhasInstallation\x12-\n" +
	"\x12installation_price\x18\x02 \x01(\x01R\x11installationPrice\x12*\n" +
	"\x11home_region_price\x18\x03 \x01(\x01R\x0fhomeRegionPrice\x12-\n" +
	"\x13is_home_region_free\x18\x04 \x01(\bR\x10isHomeRegionFree\x12,\n" +
	"\x12home_delivery_days\x18\x05 \x01(\tR\x10homeDeliveryDays\x12D\n" +
	"\x0fregional_prices\x18\x06 \x03(\v2\x1b.product.RegionalPriceGroupR\x0eregionalPrices\"\xb2\x01\n" +
	"\x0eProductVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12%\n" +
	"\x0eprice_modifier\x18\x03 \x01(\x01R\rpriceModifier\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\"\xaa\x06\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12,\n" +
	"\x04name\x18\x04 \x01(\v2\x18.product.LocalizedStringR\x04name\x12:\n" +
	"\vdescription\x18\x05 \x01(\v2\x18.product.LocalizedStringR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12%\n" +
	"\x0ediscount_price\x18\a \x01(\x01R\rdiscountPrice\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x12-\n" +
	"\x05specs\x18\t \x01(\v2\x17.google.protobuf.StructR\x05specs\x123\n" +
	"\bvariants\x18\n" +
	" \x03(\v2\x17.product.ProductVariantR\bvariants\x12F\n" +
	"\x11delivery_settings\x18\v \x01(\v2\x19.product.DeliverySettingsR\x10deliverySettings\x12\x16\n" +
	"\x06rating\x18\f \x01(\x01R\x06rating\x12\x1d\n" +
	"\n" +
	"view_count\x18\r \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"sold_count\x18\x0e \x01(\x05R\tsoldCount\x12\x15\n" +
	"\x06is_new\x18\x0f \x01(\bR\x05isNew\x12\x1d\n" +
	"\n" +
	"is_popular\x18\x10 \x01(\bR\tisPopular\x12\x1b\n" +
	"\tis_active\x18\x11 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10discount_percent\x18\x13 \x01(\x05R\x0fdiscountPercent\x12!\n" +
	"\fhas_discount\x18\x14 \x01(\bR\vhasDiscount\x12\x1b\n" +
	"\tshop_name\x18\x15 \x01(\tR\bshopName\x12\x1b\n" +
	"\tshop_logo\x18\x16 \x01(\tR\bshopLogo\"\x88\x02\n" +
	"\x0eProductFilters\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNew\x12\x1d\n" +
	"\n" +
	"is_popular\x18\x04 \x01(\bR\tisPopular\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1b\n" +
	"\tmin_price\x18\x06 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\a \x01(\x01R\bmaxPrice\x12\x16\n" +
	"\x06search\x18\b \x01(\tR\x06search\x12\x17\n" +
	"\asort_by\x18\t \x01(\tR\x06sortBy\"r\n" +
	"\x13ListProductsRequest\x121\n" +
	"\afilters\x18\x01 \x01(\v2\x17.product.ProductFiltersR\afilters\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x84\x01\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"J\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eincrement_view\x18\x02 \x01(\bR\rincrementView\"=\n" +
	"\x0fProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"\x8e\x04\n" +
	"\x14CreateProductRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12,\n" +
	"\x04name\x18\x03 \x01(\v2\x18.product.LocalizedStringR\x04name\x12:\n" +
	"\vdescription\x18\x04 \x01(\v2\x18.product.LocalizedStringR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x06 \x01(\x01R\rdiscountPrice\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12-\n" +
	"\x05specs\x18\b \x01(\v2\x17.google.protobuf.StructR\x05specs\x123\n" +
	"\bvariants\x18\t \x03(\v2\x17.product.ProductVariantR\bvariants\x12F\n" +
	"\x11delivery_settings\x18\n" +
	" \x01(\v2\x19.product.DeliverySettingsR\x10deliverySettings\x12\x15\n" +
	"\x06is_new\x18\v \x01(\bR\x05isNew\x12\x1d\n" +
	"\n" +
	"is_popular\x18\f \x01(\bR\tisPopular\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\"\xb6\x05\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x121\n" +
	"\x04name\x18\x03 \x01(\v2\x18.product.LocalizedStringH\x01R\x04name\x88\x01\x01\x12?\n" +
	"\vdescription\x18\x04 \x01(\v2\x18.product.LocalizedStringH\x02R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x03R\x05price\x88\x01\x01\x12*\n" +
	"\x0ediscount_price\x18\x06 \x01(\x01H\x04R\rdiscountPrice\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12-\n" +
	"\x05specs\x18\b \x01(\v2\x17.google.protobuf.StructR\x05specs\x123\n" +
	"\bvariants\x18\t \x03(\v2\x17.product.ProductVariantR\bvariants\x12K\n" +
	"\x11delivery_settings\x18\n" +
	" \x01(\v2\x19.product.DeliverySettingsH\x05R\x10deliverySettings\x88\x01\x01\x12\x1a\n" +
	"\x06is_new\x18\v \x01(\bH\x06R\x05isNew\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_popular\x18\f \x01(\bH\aR\tisPopular\x88\x01\x01\x12 \n" +
	"\tis_active\x18\r \x01(\bH\bR\bisActive\x88\x01\x01B\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_priceB\x11\n" +
	"\x0f_discount_priceB\x14\n" +
	"\x12_delivery_settingsB\t\n" +
	"\a_is_newB\r\n" +
	"\v_is_popularB\f\n" +
	"\n" +
	"_is_active\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x1aToggleProductStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\"j\n" +
	"\x12UploadImageRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.product.ImageMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x86\x01\n" +
	"\rImageMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\tR\x06shopId\"f\n" +
	"\x13UploadImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"m\n" +
	"\x18BulkUploadImagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x02 \x03(\tR\timageUrls\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\x16ListNewArrivalsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\"S\n" +
	"\x1aListPopularProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\"\xfb\x01\n" +
	"\x15CategoryProductsGroup\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12=\n" +
	"\rcategory_name\x18\x02 \x01(\v2\x18.product.LocalizedStringR\fcategoryName\x12#\n" +
	"\rcategory_slug\x18\x03 \x01(\tR\fcategorySlug\x12,\n" +
	"\bproducts\x18\x04 \x03(\v2\x10.product.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x06 \x01(\bR\ahasMore\"\x8b\x01\n" +
	"'ListProductsGroupedBySubcategoryRequest\x12,\n" +
	"\x12parent_category_id\x18\x01 \x01(\tR\x10parentCategoryId\x122\n" +
	"\x15products_per_category\x18\x02 \x01(\x05R\x13productsPerCategory\"x\n" +
	"(ListProductsGroupedBySubcategoryResponse\x126\n" +
	"\x06groups\x18\x01 \x03(\v2\x1e.product.CategoryProductsGroupR\x06groups\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x91\x01\n" +
	"\x19ListSellerProductsRequest\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\tR\x06shopId\x121\n" +
	"\afilters\x18\x02 \x01(\v2\x17.product.ProductFiltersR\afilters\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\a\n" +
	"\x05Empty2\x88\b\n" +
	"\x0eProductService\x12B\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12Q\n" +
	"\x0fListNewArrivals\x12\x1f.product.ListNewArrivalsRequest\x1a\x1d.product.ListProductsResponse\x12Y\n" +
	"\x13ListPopularProducts\x12#.product.ListPopularProductsRequest\x1a\x1d.product.ListProductsResponse\x12\x87\x01\n" +
	" ListProductsGroupedBySubcategory\x120.product.ListProductsGroupedBySubcategoryRequest\x1a1.product.ListProductsGroupedBySubcategoryResponse\x12W\n" +
	"\x12ListSellerProducts\x12\".product.ListSellerProductsRequest\x1a\x1d.product.ListProductsResponse\x12H\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12H\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x18.product.ProductResponse\x12>\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x0e.product.Empty\x12T\n" +
	"\x13ToggleProductStatus\x12#.product.ToggleProductStatusRequest\x1a\x18.product.ProductResponse\x12Q\n" +
	"\x12UploadProductImage\x12\x1b.product.UploadImageRequest\x1a\x1c.product.UploadImageResponse(\x01\x12W\n" +
	"\x13UploadProductImages\x12\x1b.product.UploadImageRequest\x1a!.product.BulkUploadImagesResponse(\x01B\x1cZ\x1amebellar-backend/pkg/pb;pbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_product_proto_goTypes = []any{
	(*LocalizedString)(nil),                          // 0: product.LocalizedString
	(*RegionalPriceGroup)(nil),                       // 1: product.RegionalPriceGroup
	(*DeliverySettings)(nil),                         // 2: product.DeliverySettings
	(*ProductVariant)(nil),                           // 3: product.ProductVariant
	(*Product)(nil),                                  // 4: product.Product
	(*ProductFilters)(nil),                           // 5: product.ProductFilters
	(*ListProductsRequest)(nil),                      // 6: product.ListProductsRequest
	(*ListProductsResponse)(nil),                     // 7: product.ListProductsResponse
	(*GetProductRequest)(nil),                        // 8: product.GetProductRequest
	(*ProductResponse)(nil),                          // 9: product.ProductResponse
	(*CreateProductRequest)(nil),                     // 10: product.CreateProductRequest
	(*UpdateProductRequest)(nil),                     // 11: product.UpdateProductRequest
	(*DeleteProductRequest)(nil),                     // 12: product.DeleteProductRequest
	(*ToggleProductStatusRequest)(nil),               // 13: product.ToggleProductStatusRequest
	(*UploadImageRequest)(nil),                       // 14: product.UploadImageRequest
	(*ImageMetadata)(nil),                            // 15: product.ImageMetadata
	(*UploadImageResponse)(nil),                      // 16: product.UploadImageResponse
	(*BulkUploadImagesResponse)(nil),                 // 17: product.BulkUploadImagesResponse
	(*ListNewArrivalsRequest)(nil),                   // 18: product.ListNewArrivalsRequest
	(*ListPopularProductsRequest)(nil),               // 19: product.ListPopularProductsRequest
	(*CategoryProductsGroup)(nil),                    // 20: product.CategoryProductsGroup
	(*ListProductsGroupedBySubcategoryRequest)(nil),  // 21: product.ListProductsGroupedBySubcategoryRequest
	(*ListProductsGroupedBySubcategoryResponse)(nil), // 22: product.ListProductsGroupedBySubcategoryResponse
	(*ListSellerProductsRequest)(nil),                // 23: product.ListSellerProductsRequest
	(*Empty)(nil),                                    // 24: product.Empty
	(*structpb.Struct)(nil),                          // 25: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                    // 26: google.protobuf.Timestamp
}
var file_product_proto_depIdxs = []int32{
	1,  // 0: product.DeliverySettings.regional_prices:type_name -> product.RegionalPriceGroup
	25, // 1: product.ProductVariant.attributes:type_name -> google.protobuf.Struct
	0,  // 2: product.Product.name:type_name -> product.LocalizedString
	0,  // 3: product.Product.description:type_name -> product.LocalizedString
	25, // 4: product.Product.specs:type_name -> google.protobuf.Struct
	3,  // 5: product.Product.variants:type_name -> product.ProductVariant
	2,  // 6: product.Product.delivery_settings:type_name -> product.DeliverySettings
	26, // 7: product.Product.created_at:type_name -> google.protobuf.Timestamp
	5,  // 8: product.ListProductsRequest.filters:type_name -> product.ProductFilters
	4,  // 9: product.ListProductsResponse.products:type_name -> product.Product
	4,  // 10: product.ProductResponse.product:type_name -> product.Product
	0,  // 11: product.CreateProductRequest.name:type_name -> product.LocalizedString
	0,  // 12: product.CreateProductRequest.description:type_name -> product.LocalizedString
	25, // 13: product.CreateProductRequest.specs:type_name -> google.protobuf.Struct
	3,  // 14: product.CreateProductRequest.variants:type_name -> product.ProductVariant
	2,  // 15: product.CreateProductRequest.delivery_settings:type_name -> product.DeliverySettings
	0,  // 16: product.UpdateProductRequest.name:type_name -> product.LocalizedString
	0,  // 17: product.UpdateProductRequest.description:type_name -> product.LocalizedString
	25, // 18: product.UpdateProductRequest.specs:type_name -> google.protobuf.Struct
	3,  // 19: product.UpdateProductRequest.variants:type_name -> product.ProductVariant
	2,  // 20: product.UpdateProductRequest.delivery_settings:type_name -> product.DeliverySettings
	15, // 21: product.UploadImageRequest.metadata:type_name -> product.ImageMetadata
	0,  // 22: product.CategoryProductsGroup.category_name:type_name -> product.LocalizedString
	4,  // 23: product.CategoryProductsGroup.products:type_name -> product.Product
	20, // 24: product.ListProductsGroupedBySubcategoryResponse.groups:type_name -> product.CategoryProductsGroup
	5,  // 25: product.ListSellerProductsRequest.filters:type_name -> product.ProductFilters
	8,  // 26: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	6,  // 27: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	18, // 28: product.ProductService.ListNewArrivals:input_type -> product.ListNewArrivalsRequest
	19, // 29: product.ProductService.ListPopularProducts:input_type -> product.ListPopularProductsRequest
	21, // 30: product.ProductService.ListProductsGroupedBySubcategory:input_type -> product.ListProductsGroupedBySubcategoryRequest
	23, // 31: product.ProductService.ListSellerProducts:input_type -> product.ListSellerProductsRequest
	10, // 32: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	11, // 33: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	12, // 34: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	13, // 35: product.ProductService.ToggleProductStatus:input_type -> product.ToggleProductStatusRequest
	14, // 36: product.ProductService.UploadProductImage:input_type -> product.UploadImageRequest
	14, // 37: product.ProductService.UploadProductImages:input_type -> product.UploadImageRequest
	9,  // 38: product.ProductService.GetProduct:output_type -> product.ProductResponse
	7,  // 39: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	7,  // 40: product.ProductService.ListNewArrivals:output_type -> product.ListProductsResponse
	7,  // 41: product.ProductService.ListPopularProducts:output_type -> product.ListProductsResponse
	22, // 42: product.ProductService.ListProductsGroupedBySubcategory:output_type -> product.ListProductsGroupedBySubcategoryResponse
	7,  // 43: product.ProductService.ListSellerProducts:output_type -> product.ListProductsResponse
	9,  // 44: product.ProductService.CreateProduct:output_type -> product.ProductResponse
	9,  // 45: product.ProductService.UpdateProduct:output_type -> product.ProductResponse
	24, // 46: product.ProductService.DeleteProduct:output_type -> product.Empty
	9,  // 47: product.ProductService.ToggleProductStatus:output_type -> product.ProductResponse
	16, // 48: product.ProductService.UploadProductImage:output_type -> product.UploadImageResponse
	17, // 49: product.ProductService.UploadProductImages:output_type -> product.BulkUploadImagesResponse
	38, // [38:50] is the sub-list for method output_type
	26, // [26:38] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	file_product_proto_msgTypes[11].OneofWrappers = []any{}
	file_product_proto_msgTypes[14].OneofWrappers = []any{
		(*UploadImageRequest_Metadata)(nil),
		(*UploadImageRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
