// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: shop.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopService_GetShopBySlug_FullMethodName          = "/shop.ShopService/GetShopBySlug"
	ShopService_GetPublicSellerProfile_FullMethodName = "/shop.ShopService/GetPublicSellerProfile"
	ShopService_GetMyShops_FullMethodName             = "/shop.ShopService/GetMyShops"
	ShopService_GetShop_FullMethodName                = "/shop.ShopService/GetShop"
	ShopService_CreateShop_FullMethodName             = "/shop.ShopService/CreateShop"
	ShopService_UpdateShop_FullMethodName             = "/shop.ShopService/UpdateShop"
	ShopService_DeleteShop_FullMethodName             = "/shop.ShopService/DeleteShop"
	ShopService_GetSellerProfile_FullMethodName       = "/shop.ShopService/GetSellerProfile"
	ShopService_UpgradeToSeller_FullMethodName        = "/shop.ShopService/UpgradeToSeller"
	ShopService_UpdateSellerProfile_FullMethodName    = "/shop.ShopService/UpdateSellerProfile"
	ShopService_UpdateLegalInfo_FullMethodName        = "/shop.ShopService/UpdateLegalInfo"
	ShopService_DeleteSellerAccount_FullMethodName    = "/shop.ShopService/DeleteSellerAccount"
	ShopService_UploadShopImage_FullMethodName        = "/shop.ShopService/UploadShopImage"
	ShopService_AdminListShops_FullMethodName         = "/shop.ShopService/AdminListShops"
	ShopService_AdminGetShop_FullMethodName           = "/shop.ShopService/AdminGetShop"
	ShopService_AdminUpdateShop_FullMethodName        = "/shop.ShopService/AdminUpdateShop"
	ShopService_AdminDeleteShop_FullMethodName        = "/shop.ShopService/AdminDeleteShop"
)

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopServiceClient interface {
	// Public endpoints
	GetShopBySlug(ctx context.Context, in *GetShopBySlugRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	GetPublicSellerProfile(ctx context.Context, in *GetPublicSellerProfileRequest, opts ...grpc.CallOption) (*PublicSellerProfileResponse, error)
	// Seller endpoints (requires auth + seller role)
	GetMyShops(ctx context.Context, in *GetMyShopsRequest, opts ...grpc.CallOption) (*GetMyShopsResponse, error)
	GetShop(ctx context.Context, in *GetShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	UpdateShop(ctx context.Context, in *UpdateShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	DeleteShop(ctx context.Context, in *DeleteShopRequest, opts ...grpc.CallOption) (*Empty, error)
	// Seller profile management
	GetSellerProfile(ctx context.Context, in *GetSellerProfileRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error)
	UpgradeToSeller(ctx context.Context, in *UpgradeToSellerRequest, opts ...grpc.CallOption) (*UpgradeToSellerResponse, error)
	UpdateSellerProfile(ctx context.Context, in *UpdateSellerProfileRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error)
	UpdateLegalInfo(ctx context.Context, in *UpdateLegalInfoRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error)
	DeleteSellerAccount(ctx context.Context, in *DeleteSellerAccountRequest, opts ...grpc.CallOption) (*DeleteSellerAccountResponse, error)
	// Shop image upload via streaming
	UploadShopImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadShopImageRequest, UploadShopImageResponse], error)
	// Admin endpoints (requires admin/moderator role)
	AdminListShops(ctx context.Context, in *AdminListShopsRequest, opts ...grpc.CallOption) (*ListShopsResponse, error)
	AdminGetShop(ctx context.Context, in *GetShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	AdminUpdateShop(ctx context.Context, in *AdminUpdateShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	AdminDeleteShop(ctx context.Context, in *DeleteShopRequest, opts ...grpc.CallOption) (*Empty, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) GetShopBySlug(ctx context.Context, in *GetShopBySlugRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, ShopService_GetShopBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetPublicSellerProfile(ctx context.Context, in *GetPublicSellerProfileRequest, opts ...grpc.CallOption) (*PublicSellerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicSellerProfileResponse)
	err := c.cc.Invoke(ctx, ShopService_GetPublicSellerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetMyShops(ctx context.Context, in *GetMyShopsRequest, opts ...grpc.CallOption) (*GetMyShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyShopsResponse)
	err := c.cc.Invoke(ctx, ShopService_GetMyShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShop(ctx context.Context, in *GetShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, ShopService_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, ShopService_CreateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateShop(ctx context.Context, in *UpdateShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, ShopService_UpdateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) DeleteShop(ctx context.Context, in *DeleteShopRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShopService_DeleteShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetSellerProfile(ctx context.Context, in *GetSellerProfileRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellerProfileResponse)
	err := c.cc.Invoke(ctx, ShopService_GetSellerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpgradeToSeller(ctx context.Context, in *UpgradeToSellerRequest, opts ...grpc.CallOption) (*UpgradeToSellerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeToSellerResponse)
	err := c.cc.Invoke(ctx, ShopService_UpgradeToSeller_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateSellerProfile(ctx context.Context, in *UpdateSellerProfileRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellerProfileResponse)
	err := c.cc.Invoke(ctx, ShopService_UpdateSellerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateLegalInfo(ctx context.Context, in *UpdateLegalInfoRequest, opts ...grpc.CallOption) (*SellerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellerProfileResponse)
	err := c.cc.Invoke(ctx, ShopService_UpdateLegalInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) DeleteSellerAccount(ctx context.Context, in *DeleteSellerAccountRequest, opts ...grpc.CallOption) (*DeleteSellerAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSellerAccountResponse)
	err := c.cc.Invoke(ctx, ShopService_DeleteSellerAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UploadShopImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadShopImageRequest, UploadShopImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShopService_ServiceDesc.Streams[0], ShopService_UploadShopImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadShopImageRequest, UploadShopImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShopService_UploadShopImageClient = grpc.ClientStreamingClient[UploadShopImageRequest, UploadShopImageResponse]

func (c *shopServiceClient) AdminListShops(ctx context.Context, in *AdminListShopsRequest, opts ...grpc.CallOption) (*ListShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopsResponse)
	err := c.cc.Invoke(ctx, ShopService_AdminListShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) AdminGetShop(ctx context.Context, in *GetShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, ShopService_AdminGetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) AdminUpdateShop(ctx context.Context, in *AdminUpdateShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, ShopService_AdminUpdateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) AdminDeleteShop(ctx context.Context, in *DeleteShopRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShopService_AdminDeleteShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility.
type ShopServiceServer interface {
	// Public endpoints
	GetShopBySlug(context.Context, *GetShopBySlugRequest) (*ShopResponse, error)
	GetPublicSellerProfile(context.Context, *GetPublicSellerProfileRequest) (*PublicSellerProfileResponse, error)
	// Seller endpoints (requires auth + seller role)
	GetMyShops(context.Context, *GetMyShopsRequest) (*GetMyShopsResponse, error)
	GetShop(context.Context, *GetShopRequest) (*ShopResponse, error)
	CreateShop(context.Context, *CreateShopRequest) (*ShopResponse, error)
	UpdateShop(context.Context, *UpdateShopRequest) (*ShopResponse, error)
	DeleteShop(context.Context, *DeleteShopRequest) (*Empty, error)
	// Seller profile management
	GetSellerProfile(context.Context, *GetSellerProfileRequest) (*SellerProfileResponse, error)
	UpgradeToSeller(context.Context, *UpgradeToSellerRequest) (*UpgradeToSellerResponse, error)
	UpdateSellerProfile(context.Context, *UpdateSellerProfileRequest) (*SellerProfileResponse, error)
	UpdateLegalInfo(context.Context, *UpdateLegalInfoRequest) (*SellerProfileResponse, error)
	DeleteSellerAccount(context.Context, *DeleteSellerAccountRequest) (*DeleteSellerAccountResponse, error)
	// Shop image upload via streaming
	UploadShopImage(grpc.ClientStreamingServer[UploadShopImageRequest, UploadShopImageResponse]) error
	// Admin endpoints (requires admin/moderator role)
	AdminListShops(context.Context, *AdminListShopsRequest) (*ListShopsResponse, error)
	AdminGetShop(context.Context, *GetShopRequest) (*ShopResponse, error)
	AdminUpdateShop(context.Context, *AdminUpdateShopRequest) (*ShopResponse, error)
	AdminDeleteShop(context.Context, *DeleteShopRequest) (*Empty, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopServiceServer struct{}

func (UnimplementedShopServiceServer) GetShopBySlug(context.Context, *GetShopBySlugRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopBySlug not implemented")
}
func (UnimplementedShopServiceServer) GetPublicSellerProfile(context.Context, *GetPublicSellerProfileRequest) (*PublicSellerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicSellerProfile not implemented")
}
func (UnimplementedShopServiceServer) GetMyShops(context.Context, *GetMyShopsRequest) (*GetMyShopsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyShops not implemented")
}
func (UnimplementedShopServiceServer) GetShop(context.Context, *GetShopRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedShopServiceServer) CreateShop(context.Context, *CreateShopRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShop not implemented")
}
func (UnimplementedShopServiceServer) UpdateShop(context.Context, *UpdateShopRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShop not implemented")
}
func (UnimplementedShopServiceServer) DeleteShop(context.Context, *DeleteShopRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShop not implemented")
}
func (UnimplementedShopServiceServer) GetSellerProfile(context.Context, *GetSellerProfileRequest) (*SellerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSellerProfile not implemented")
}
func (UnimplementedShopServiceServer) UpgradeToSeller(context.Context, *UpgradeToSellerRequest) (*UpgradeToSellerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeToSeller not implemented")
}
func (UnimplementedShopServiceServer) UpdateSellerProfile(context.Context, *UpdateSellerProfileRequest) (*SellerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSellerProfile not implemented")
}
func (UnimplementedShopServiceServer) UpdateLegalInfo(context.Context, *UpdateLegalInfoRequest) (*SellerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLegalInfo not implemented")
}
func (UnimplementedShopServiceServer) DeleteSellerAccount(context.Context, *DeleteSellerAccountRequest) (*DeleteSellerAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSellerAccount not implemented")
}
func (UnimplementedShopServiceServer) UploadShopImage(grpc.ClientStreamingServer[UploadShopImageRequest, UploadShopImageResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadShopImage not implemented")
}
func (UnimplementedShopServiceServer) AdminListShops(context.Context, *AdminListShopsRequest) (*ListShopsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListShops not implemented")
}
func (UnimplementedShopServiceServer) AdminGetShop(context.Context, *GetShopRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetShop not implemented")
}
func (UnimplementedShopServiceServer) AdminUpdateShop(context.Context, *AdminUpdateShopRequest) (*ShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateShop not implemented")
}
func (UnimplementedShopServiceServer) AdminDeleteShop(context.Context, *DeleteShopRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteShop not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}
func (UnimplementedShopServiceServer) testEmbeddedByValue()                     {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	// If the following call panics, it indicates UnimplementedShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_GetShopBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShopBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShopBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShopBySlug(ctx, req.(*GetShopBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetPublicSellerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicSellerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetPublicSellerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetPublicSellerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetPublicSellerProfile(ctx, req.(*GetPublicSellerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetMyShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetMyShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetMyShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetMyShops(ctx, req.(*GetMyShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShop(ctx, req.(*GetShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateShop(ctx, req.(*CreateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateShop(ctx, req.(*UpdateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_DeleteShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).DeleteShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_DeleteShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).DeleteShop(ctx, req.(*DeleteShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetSellerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetSellerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetSellerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetSellerProfile(ctx, req.(*GetSellerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpgradeToSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeToSellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpgradeToSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpgradeToSeller_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpgradeToSeller(ctx, req.(*UpgradeToSellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateSellerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSellerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateSellerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateSellerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateSellerProfile(ctx, req.(*UpdateSellerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateLegalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLegalInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateLegalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateLegalInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateLegalInfo(ctx, req.(*UpdateLegalInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_DeleteSellerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSellerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).DeleteSellerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_DeleteSellerAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).DeleteSellerAccount(ctx, req.(*DeleteSellerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UploadShopImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShopServiceServer).UploadShopImage(&grpc.GenericServerStream[UploadShopImageRequest, UploadShopImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShopService_UploadShopImageServer = grpc.ClientStreamingServer[UploadShopImageRequest, UploadShopImageResponse]

func _ShopService_AdminListShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).AdminListShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_AdminListShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).AdminListShops(ctx, req.(*AdminListShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_AdminGetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).AdminGetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_AdminGetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).AdminGetShop(ctx, req.(*GetShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_AdminUpdateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).AdminUpdateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_AdminUpdateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).AdminUpdateShop(ctx, req.(*AdminUpdateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_AdminDeleteShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).AdminDeleteShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_AdminDeleteShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).AdminDeleteShop(ctx, req.(*DeleteShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShopBySlug",
			Handler:    _ShopService_GetShopBySlug_Handler,
		},
		{
			MethodName: "GetPublicSellerProfile",
			Handler:    _ShopService_GetPublicSellerProfile_Handler,
		},
		{
			MethodName: "GetMyShops",
			Handler:    _ShopService_GetMyShops_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _ShopService_GetShop_Handler,
		},
		{
			MethodName: "CreateShop",
			Handler:    _ShopService_CreateShop_Handler,
		},
		{
			MethodName: "UpdateShop",
			Handler:    _ShopService_UpdateShop_Handler,
		},
		{
			MethodName: "DeleteShop",
			Handler:    _ShopService_DeleteShop_Handler,
		},
		{
			MethodName: "GetSellerProfile",
			Handler:    _ShopService_GetSellerProfile_Handler,
		},
		{
			MethodName: "UpgradeToSeller",
			Handler:    _ShopService_UpgradeToSeller_Handler,
		},
		{
			MethodName: "UpdateSellerProfile",
			Handler:    _ShopService_UpdateSellerProfile_Handler,
		},
		{
			MethodName: "UpdateLegalInfo",
			Handler:    _ShopService_UpdateLegalInfo_Handler,
		},
		{
			MethodName: "DeleteSellerAccount",
			Handler:    _ShopService_DeleteSellerAccount_Handler,
		},
		{
			MethodName: "AdminListShops",
			Handler:    _ShopService_AdminListShops_Handler,
		},
		{
			MethodName: "AdminGetShop",
			Handler:    _ShopService_AdminGetShop_Handler,
		},
		{
			MethodName: "AdminUpdateShop",
			Handler:    _ShopService_AdminUpdateShop_Handler,
		},
		{
			MethodName: "AdminDeleteShop",
			Handler:    _ShopService_AdminDeleteShop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadShopImage",
			Handler:       _ShopService_UploadShopImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "shop.proto",
}
